import { loadLesson } from './notion-adapter.js';
const app=document.querySelector('#app'),shell=document.querySelector('.shell'),nav=document.querySelector('#section-nav'),content=document.querySelector('#lesson-content'),loading=document.querySelector('.loading-state'),error=document.querySelector('#error-state'),previous=document.querySelector('#previous'),next=document.querySelector('#next'),nextHint=document.querySelector('#next-hint'),label=document.querySelector('#progress-label'),bar=document.querySelector('#progress-bar');let lesson,sections=[],active=0;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const mathText=s=>String(s??'')
  .replace(/\\mathbb\{Z\}/g,'ℤ').replace(/\\mathbb\s*Z/g,'ℤ')
  .replace(/\\text\{([^{}]*)\}/g,'$1').replace(/\\qquad/g,'   ')
  .replace(/\\bigl|\\bigr|\\left|\\right/g,'').replace(/\\in/g,'∈')
  .replace(/\\,/g,' ').replace(/\\;/g,' ').replace(/\\!/g,'');
const inline=s=>esc(mathText(s)).replace(/@@MATH:(.*?)@@/g,(_,expr)=>`<span class="math-inline" role="math">${esc(mathText(expr))}</span>`).replace(/\*\*(.+?)\*\*/g,'<strong>$1</strong>').replace(/\*(.+?)\*/g,'<em>$1</em>').replace(/__([^_]+?)__/g,'<u>$1</u>');
function idFor(t,u){let b=t.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'section',i=b,n=2;while(u.has(i))i=`${b}-${n++}`;u.add(i);return i}
function activity(b){let m=b.metadata||{},t=m.activityType;if(!t)return'<div class="block unsupported"><strong>Incomplete activity</strong><div>Missing explicit activity type; shown without invented controls.</div></div>';let options=(m.options||[]).map(o=>`<label class="activity-option"><input type="radio" name="${esc(b.id)}" value="${esc(o.id)}"><span>${esc(o.label)}</span></label>`).join('');let control=['multiple-choice','predict'].includes(t)?`<div class="activity-options">${options}</div>`:t==='select-highlight'?`<div class="activity-options highlight-options">${(m.options||[]).map(o=>`<button class="highlight-chip" type="button">${esc(o.label)}</button>`).join('')}</div>`:t==='drag-drop'?'<div class="drag-options"><span draggable="true">12</span><span draggable="true">7</span><span draggable="true">18</span></div><div class="drop-targets"><div tabindex="0">Even</div><div tabindex="0">Odd</div></div>':t==='number-line'?'<input class="number-line" type="range" min="-10" max="10" value="0" aria-label="Number line value"><output class="line-value">0</output>':t==='explain'?'<textarea class="activity-input" aria-label="Your explanation" rows="3"></textarea>':`<input class="activity-input" aria-label="${esc(t)} input" placeholder="Interactive preview control">`;return`<section class="block activity" data-activity-type="${esc(t)}"><span class="activity-label">${esc(t.replaceAll('-',' '))}</span><p>${esc(b.text)}</p>${control}<button class="button primary activity-submit" type="button">Submit</button><div class="activity-feedback" role="status" hidden></div></section>`}
function block(b){let t=inline(b.text);if(b.metadata?.placeholder)return`<p class="block placeholder">${t}</p>`;switch(b.type){case'paragraph':return`<p class="block">${t}</p>`;case'bulleted-list':case'numbered-list':return`<${b.type==='bulleted-list'?'ul':'ol'} class="block list">${t?`<li>${t}</li>`:''}${(b.children||[]).map(c=>`<li>${block(c)}</li>`).join('')}</${b.type==='bulleted-list'?'ul':'ol'}>`;case'equation':return`<div class="block equation" role="math" aria-label="${esc(b.text)}">${t}</div>`;case'callout':case'recap':return`<aside class="block callout">${b.metadata?.icon?`<span class="callout-icon" aria-hidden="true">${esc(b.metadata.icon)}</span>`:''}<div>${t}${(b.children||[]).map(block).join('')}</div></aside>`;case'media':return b.metadata?.url?`<figure class="block learning-media"><img src="${esc(b.metadata.url)}" alt="${esc(b.metadata.alt||b.text)}"><figcaption>${t}</figcaption></figure>`:`<div class="block unsupported"><strong>Media source unavailable</strong></div>`;case'checkbox':return`<label class="block"><input type="checkbox" ${b.metadata?.checked?'checked':''} disabled> ${t}</label>`;case'activity':return activity(b);case'toggle':return`<details class="block reveal"><summary>${t||'Show solution or reasoning'}</summary>${(b.children||[]).map(block).join('')}</details>`;case'heading-3':case'heading-4':let h=b.type.slice(-1);return`<h${h} class="nested-heading">${t}</h${h}>`;case'divider':return'<hr class="block">';default:return (!t && !(b.children||[]).length) ? '' : `<div class="block unsupported"><strong>Unsupported block: ${esc(b.type)}</strong></div>`}}
let templateActivityCount=0;
const interactionMarker=/ACE_INTERACTION:\s*(predict|multiple-choice|number-input|drag-and-drop)\b/i;
const interactionField=/^(Question|Option \d+|Correct option|Correct options|Correct answer|Item \d+|Items|Bucket \d+|Buckets|Correct placement)\s*:?\s*(.*)$/i;
const numbered=(fields,prefix)=>Object.keys(fields).filter(key=>new RegExp(`^${prefix} \\d+$`).test(key)).sort((a,b)=>Number(a.slice(prefix.length+1))-Number(b.slice(prefix.length+1)));
function readInteractionFields(blocks,start){const first=blocks[start],marker=String(first.text||'').match(interactionMarker);if(!marker)return null;const type=marker[1].toLowerCase(),fields={},add=(key,value)=>{fields[key]=String(value||'').trim()},nextNumber=prefix=>numbered(fields,prefix).length+1;let mode='',end=start;const consumeLine=line=>{const value=String(line||'').trim();if(!value)return true;const match=value.match(interactionField);if(match){const key=match[1].toLowerCase(),content=match[2].trim();if(key==='items'){mode='items';if(content)add(`item ${nextNumber('item')}`,content);return true}if(key==='buckets'){mode='buckets';if(content)add(`bucket ${nextNumber('bucket')}`,content);return true}if(key==='correct placement'){mode='placement';if(content)add('correct placement',content);return true}if(/^bucket \d+$/.test(key)){mode='bucket-value';if(content)add(key,content);else fields.__pendingBucket=key;return true}add(key,content);mode='';return true}if(type!=='drag-and-drop')return false;if(mode==='items'){add(`item ${nextNumber('item')}`,value);return true}if(mode==='buckets'){add(`bucket ${nextNumber('bucket')}`,value);return true}if(mode==='bucket-value'&&fields.__pendingBucket){add(fields.__pendingBucket,value);delete fields.__pendingBucket;mode='';return true}if(mode==='placement'&&/^.+?(?::|[-–—]).+$/.test(value)){add('correct placement',[fields['correct placement'],value].filter(Boolean).join('\n'));return true}return false};const consume=text=>{const lines=String(text||'').replace(/\r/g,'').split('\n');let consumed=false;for(const line of lines){if(!consumeLine(line))return false;consumed=true}return consumed};consume(String(first.text||'').replace(marker[0],'').trim());end=start+1;while(end<blocks.length&&blocks[end].type==='paragraph'&&consume(blocks[end].text))end++;delete fields.__pendingBucket;return{type,fields,end,sourceId:first.id}}
const placementMap=value=>Object.fromEntries(String(value||'').split(/\n|;/).map(line=>line.match(/^\s*(.+?)\s*(?::|[-–—])\s*(.+)\s*$/)).filter(Boolean).map(([,bucket,items])=>[bucket.trim(),items.split(',').map(item=>item.trim()).filter(Boolean)]));
function interactionMarkup(type,fields,sourceId=''){const options=numbered(fields,'option'),items=numbered(fields,'item'),buckets=numbered(fields,'bucket'),correct=type==='number-input'?(fields['correct answer']||fields['correct option']||''):(fields['correct options']||fields['correct option']||fields['correct answer']||'');const label=type==='predict'?'Predict':type==='multiple-choice'?'Multiple choice':type==='number-input'?'Number input':'Drag and drop';const id=`template-${++templateActivityCount}`,identity=` data-interaction-id="${esc(sourceId||id)}"`;const checkButton='<button class="button primary template-submit" type="button">Check answer</button>';if(type==='number-input'&&fields.question)return`<section class="block activity template-activity" data-activity-type="${type}" data-correct="${esc(correct)}"${identity}><span class="activity-label">${label}</span><h3>${inline(fields.question)}</h3><div class="activity-answer-row"><input class="activity-number-input" inputmode="decimal" aria-label="Your answer" placeholder="Enter your answer">${checkButton}</div><p class="template-feedback" aria-live="polite"></p></section>`;if((type==='predict'||type==='multiple-choice')&&fields.question&&options.length){const inputType=type==='multiple-choice'?'checkbox':'radio';return`<section class="block activity template-activity" data-activity-type="${type}" data-correct="${esc(correct)}"${identity}><span class="activity-label">${label}</span><h3>${inline(fields.question)}</h3><div class="activity-options">${options.map((key,index)=>`<label class="activity-option"><input type="${inputType}" name="${id}" value="${index}" data-option-label="${esc(fields[key])}"><span>${inline(fields[key])}</span></label>`).join('')}</div><div class="activity-answer-row">${checkButton}</div><p class="template-feedback" aria-live="polite"></p></section>`}if(type==='drag-and-drop'&&fields.question&&items.length&&buckets.length){const placement=JSON.stringify(placementMap(fields['correct placement']));return`<section class="block activity template-activity template-drag-drop" data-activity-type="${type}" data-correct-placement="${esc(placement)}"${identity}><span class="activity-label">${label}</span><h3>${inline(fields.question)}</h3><p class="drag-instruction">Drag every item into a bucket.</p><div class="template-drag-items" aria-label="Available items">${items.map(key=>`<button class="template-drag-item" type="button" draggable="true" data-item="${esc(fields[key])}">${inline(fields[key])}</button>`).join('')}</div><div class="template-drag-buckets">${buckets.map(key=>`<div class="template-drag-bucket" data-bucket="${esc(fields[key])}" tabindex="0"><strong>${inline(fields[key])}</strong><div class="template-drag-dropzone"></div></div>`).join('')}</div><div class="activity-answer-row">${checkButton}<button class="button secondary template-reset" type="button">Reset</button></div><p class="template-feedback" aria-live="polite"></p></section>`}return null}
function renderBlocks(blocks){let html='';for(let index=0;index<blocks.length;){const interaction=blocks[index]?.type==='paragraph'?readInteractionFields(blocks,index):null;if(interaction){const rendered=interactionMarkup(interaction.type,interaction.fields,interaction.sourceId);if(rendered){html+=rendered;index=interaction.end;continue}}html+=block(blocks[index]);index++}return html}
function render(){let used=new Set(),intro=[],cur=null;sections=[];for(let b of lesson.blocks){if(b.type==='heading-2'){cur={id:idFor(b.text,used),title:b.text,blocks:[]};sections.push(cur)}else(cur?cur.blocks:intro).push(b)}nav.innerHTML=sections.map((s,i)=>`<button class="nav-item ${i<active?'is-complete':''}" type="button" data-index="${i}" aria-current="${i===active}"><span class="nav-step">${i<active?'✓':i+1}</span><span>${esc(s.title)}</span></button>`).join('');const moduleLabel=lesson.module||lesson.metadata?.module||'';content.innerHTML=`<header class="lesson-header">${moduleLabel?`<div class="lesson-kicker">${esc(moduleLabel)}</div>`:''}<h1 class="lesson-title">${esc(lesson.title)}</h1><div class="lesson-header-divider" aria-hidden="true"></div></header>${renderBlocks(intro)}${sections.map((s,i)=>`<article class="section" id="${s.id}" ${i!==active?'hidden':''}>${renderBlocks(s.blocks)}</article>`).join('')}`;label.textContent=`${active+1} of ${sections.length} completed`;bar.style.width=`${(active+1)/sections.length*100}%`;previous.disabled=active===0;next.disabled=active===sections.length-1;if(nextHint)nextHint.textContent=active<sections.length-1?`Next: ${sections[active+1].title}`:'You have reached the end';document.querySelectorAll('.nav-item').forEach(x=>x.onclick=()=>{active=+x.dataset.index;render()})}
async function start(){try{const parts=location.pathname.split('/').filter(Boolean),pageId=parts[0]==='preview'&&parts[1]?decodeURIComponent(parts[1]):'even-and-odd-testing';lesson=await loadLesson(pageId);if(!lesson.blocks.length)throw Error(`Lesson ${pageId} is empty`)}catch(e){loading.hidden=true;error.hidden=false;error.innerHTML=`<strong>Unable to load this lesson.</strong><p>${esc(e.message)}</p><button class="button primary" onclick="location.reload()">Retry</button>`;return}loading.hidden=true;shell.hidden=false;render();if(new URLSearchParams(location.search).has('debug')){const d=lesson.diagnostics||[];error.hidden=false;error.className='message diagnostics';error.innerHTML=`<strong>Preview diagnostics</strong><p>Source: ${esc(lesson.source.ref)} · ${d.length} unsupported block(s)</p>${d.map(x=>`<div>${esc(x.blockId)} — ${esc(x.sourceType)}: ${esc(x.message)}</div>`).join('')||'<div>No adapter diagnostics.</div>'}`}}previous.onclick=()=>{if(active){active--;render()}};next.onclick=()=>{if(active<sections.length-1){active++;render()}};start();
document.querySelector('.sidebar-toggle')?.addEventListener('click',e=>{let open=e.currentTarget.getAttribute('aria-expanded')==='true';e.currentTarget.setAttribute('aria-expanded',String(!open));document.querySelector('#sidebar-content').hidden=open});

const visitorStorageKey='ace_anonymous_visitor_id';
function visitorId(){try{let value=localStorage.getItem(visitorStorageKey);if(!value){value=crypto.randomUUID();localStorage.setItem(visitorStorageKey,value)}return value}catch{return null}}
let persistenceWarningShown=false;
document.addEventListener('ace:interaction-checked',event=>{const activity=event.target.closest('.template-activity'),detail=event.detail;if(!activity||!detail||!lesson)return;const visitor=visitorId();if(!visitor)return;const attemptNumber=Number(activity.dataset.attemptNumber||0)+1;activity.dataset.attemptNumber=String(attemptNumber);fetch('/api/progress/attempt',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({visitorId:visitor,lessonId:lesson.id,interactionId:activity.dataset.interactionId,activityType:activity.dataset.activityType,answer:detail.answer,isCorrect:detail.isCorrect,attemptNumber})}).then(response=>{if(!response.ok)throw Error('Persistence request failed')}).catch(()=>{if(!persistenceWarningShown){persistenceWarningShown=true;console.warn('ACE progress was not saved. Configure Supabase on the server to enable persistence.')}})});
